export const SEARCH_BLUR = 'search_blur'
export const SEARCH_FOCUS = 'search_focus'
export const GET_SEARCH_LIST = 'get_search_list'
export const MOUSE_IN = 'mouse_in'
export const MOUSE_LEAVE = 'mouse_leave'
export const CHANGE_LIST = 'change_list'
